const PROFILE_ID = "11111111-1111-1111-1111-111111111111";
const SEARCH_ID = "22222222-2222-2222-2222-222222222222";
const JOB_ID = "33333333-3333-3333-3333-333333333333";

export const fixtures = {
  profile: {
    id: PROFILE_ID,
    display_name: "Gui",
    preferences: {
      query: "staff engineer",
      country: null,
      worldwide: true,
      seniority: ["Senior"],
      employment_types: ["Full Time"],
      minimum_salary: null,
      posted_within_days: null,
      sort: "relevance" as const,
    },
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  searchLoading: {
    search_id: SEARCH_ID,
    status: "loading" as const,
    progress: 0.4,
    checked_count: 400,
    page: 1,
    page_size: 100,
    total: null,
    is_complete: false,
    warnings: [],
    items: [
      {
        provider: "himalayas",
        provider_job_id: "job-1",
        title: "Staff Engineer",
        company: "Linear",
        description: "Build product infrastructure.",
        location_text: "Remote worldwide",
        employment_type: "full_time",
        remote_type: "remote",
        seniority: "Staff",
        salary_min_annual: 180000,
        salary_max_annual: 220000,
        salary_currency: "USD",
        job_url: "https://himalayas.app/jobs/1",
        posted_at: "2026-01-10T00:00:00Z",
      },
    ],
  },
  searchComplete: {
    search_id: SEARCH_ID,
    status: "complete" as const,
    progress: 1,
    checked_count: 800,
    page: 1,
    page_size: 100,
    total: 1,
    is_complete: true,
    warnings: [],
    items: [
      {
        provider: "himalayas",
        provider_job_id: "job-1",
        title: "Staff Engineer",
        company: "Linear",
        description: "Build product infrastructure.",
        location_text: "Remote worldwide",
        employment_type: "full_time",
        remote_type: "remote",
        seniority: "Staff",
        salary_min_annual: 180000,
        salary_max_annual: 220000,
        salary_currency: "USD",
        job_url: "https://himalayas.app/jobs/1",
        posted_at: "2026-01-10T00:00:00Z",
      },
    ],
  },
  searchRefreshComplete: {
    search_id: SEARCH_ID,
    status: "complete" as const,
    progress: 1,
    checked_count: 800,
    page: 1,
    page_size: 100,
    total: 1,
    is_complete: true,
    warnings: [],
    previous_search_id: null,
    serving_search_id: SEARCH_ID,
    items: [
      {
        provider: "himalayas",
        provider_job_id: "job-1",
        title: "Staff Engineer",
        company: "Linear",
        description: "Build product infrastructure.",
        location_text: "Remote worldwide",
        employment_type: "full_time",
        remote_type: "remote",
        seniority: "Staff",
        salary_min_annual: 180000,
        salary_max_annual: 220000,
        salary_currency: "USD",
        job_url: "https://himalayas.app/jobs/1",
        posted_at: "2026-01-10T00:00:00Z",
      },
    ],
  },
  savedJob: {
    id: JOB_ID,
    profile_id: PROFILE_ID,
    provider: "himalayas",
    provider_job_id: "job-1",
    state: "saved" as const,
    saved_at: "2026-01-11T00:00:00Z",
    applied_at: null,
    updated_at: "2026-01-11T00:00:00Z",
    title: "Staff Engineer",
    company: "Linear",
    description: "Build product infrastructure.",
    location_text: "Remote worldwide",
    employment_type: "full_time",
    remote_type: "remote",
    seniority: "Staff",
    salary_min_annual: 180000,
    salary_max_annual: 220000,
    salary_currency: "USD",
    job_url: "https://himalayas.app/jobs/1",
    posted_at: "2026-01-10T00:00:00Z",
  },
};

export function jsonResponse(body: unknown, status = 200) {
  return {
    status,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  };
}
